port: 7777
# pre_action: ''
# 执行命令后以0.5s间隔连续截屏20次
# post_action: 'nircmd.exe loop 20 500 savescreenshot "{PYDECK_PATH}\static\screenshot\{APPID}.png"'
apps:
-   id: 'notepad'
    program: 'notepad.exe'

-   id: 'edit_hosts'
    program: 'notepad.exe'
    argument: 'C:\Windows\System32\drivers\etc\hosts'

-   id: 'cmd'
    program: 'C:\Windows\System32\cmd.exe'
    workdir: '"C:\Program Files\"'

-   id: 'ahk'
    program: 'C:\Program Files\AutoHotkey\AutoHotkeyU64.exe'
    argument: '"D:\My Scripts\曹操快切.ahk"'
